/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BecomeRiderRouteImport } from './routes/become-rider'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRiderRouteImport } from './routes/_authenticated/rider'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBookRouteImport } from './routes/_authenticated/book'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPaymentIndexRouteImport } from './routes/_authenticated/payment.index'
import { Route as AuthenticatedTrackOrderIdRouteImport } from './routes/_authenticated/track.$orderId'
import { Route as AuthenticatedPaymentOrderIdRouteImport } from './routes/_authenticated/payment.$orderId'
import { Route as ApiPublicMpesaCallbackRouteImport } from './routes/api/public/mpesa/callback'

const BecomeRiderRoute = BecomeRiderRouteImport.update({
  id: '/become-rider',
  path: '/become-rider',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRiderRoute = AuthenticatedRiderRouteImport.update({
  id: '/rider',
  path: '/rider',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBookRoute = AuthenticatedBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentIndexRoute =
  AuthenticatedPaymentIndexRouteImport.update({
    id: '/payment/',
    path: '/payment/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTrackOrderIdRoute =
  AuthenticatedTrackOrderIdRouteImport.update({
    id: '/track/$orderId',
    path: '/track/$orderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaymentOrderIdRoute =
  AuthenticatedPaymentOrderIdRouteImport.update({
    id: '/payment/$orderId',
    path: '/payment/$orderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicMpesaCallbackRoute = ApiPublicMpesaCallbackRouteImport.update({
  id: '/api/public/mpesa/callback',
  path: '/api/public/mpesa/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/become-rider': typeof BecomeRiderRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/book': typeof AuthenticatedBookRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/rider': typeof AuthenticatedRiderRoute
  '/payment/$orderId': typeof AuthenticatedPaymentOrderIdRoute
  '/track/$orderId': typeof AuthenticatedTrackOrderIdRoute
  '/payment/': typeof AuthenticatedPaymentIndexRoute
  '/api/public/mpesa/callback': typeof ApiPublicMpesaCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/become-rider': typeof BecomeRiderRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/book': typeof AuthenticatedBookRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/rider': typeof AuthenticatedRiderRoute
  '/payment/$orderId': typeof AuthenticatedPaymentOrderIdRoute
  '/track/$orderId': typeof AuthenticatedTrackOrderIdRoute
  '/payment': typeof AuthenticatedPaymentIndexRoute
  '/api/public/mpesa/callback': typeof ApiPublicMpesaCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/become-rider': typeof BecomeRiderRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/book': typeof AuthenticatedBookRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/rider': typeof AuthenticatedRiderRoute
  '/_authenticated/payment/$orderId': typeof AuthenticatedPaymentOrderIdRoute
  '/_authenticated/track/$orderId': typeof AuthenticatedTrackOrderIdRoute
  '/_authenticated/payment/': typeof AuthenticatedPaymentIndexRoute
  '/api/public/mpesa/callback': typeof ApiPublicMpesaCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/become-rider'
    | '/admin'
    | '/book'
    | '/dashboard'
    | '/rider'
    | '/payment/$orderId'
    | '/track/$orderId'
    | '/payment/'
    | '/api/public/mpesa/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/become-rider'
    | '/admin'
    | '/book'
    | '/dashboard'
    | '/rider'
    | '/payment/$orderId'
    | '/track/$orderId'
    | '/payment'
    | '/api/public/mpesa/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/become-rider'
    | '/_authenticated/admin'
    | '/_authenticated/book'
    | '/_authenticated/dashboard'
    | '/_authenticated/rider'
    | '/_authenticated/payment/$orderId'
    | '/_authenticated/track/$orderId'
    | '/_authenticated/payment/'
    | '/api/public/mpesa/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BecomeRiderRoute: typeof BecomeRiderRoute
  ApiPublicMpesaCallbackRoute: typeof ApiPublicMpesaCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/become-rider': {
      id: '/become-rider'
      path: '/become-rider'
      fullPath: '/become-rider'
      preLoaderRoute: typeof BecomeRiderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/rider': {
      id: '/_authenticated/rider'
      path: '/rider'
      fullPath: '/rider'
      preLoaderRoute: typeof AuthenticatedRiderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/book': {
      id: '/_authenticated/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof AuthenticatedBookRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payment/': {
      id: '/_authenticated/payment/'
      path: '/payment'
      fullPath: '/payment/'
      preLoaderRoute: typeof AuthenticatedPaymentIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/track/$orderId': {
      id: '/_authenticated/track/$orderId'
      path: '/track/$orderId'
      fullPath: '/track/$orderId'
      preLoaderRoute: typeof AuthenticatedTrackOrderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payment/$orderId': {
      id: '/_authenticated/payment/$orderId'
      path: '/payment/$orderId'
      fullPath: '/payment/$orderId'
      preLoaderRoute: typeof AuthenticatedPaymentOrderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/mpesa/callback': {
      id: '/api/public/mpesa/callback'
      path: '/api/public/mpesa/callback'
      fullPath: '/api/public/mpesa/callback'
      preLoaderRoute: typeof ApiPublicMpesaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBookRoute: typeof AuthenticatedBookRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedRiderRoute: typeof AuthenticatedRiderRoute
  AuthenticatedPaymentOrderIdRoute: typeof AuthenticatedPaymentOrderIdRoute
  AuthenticatedTrackOrderIdRoute: typeof AuthenticatedTrackOrderIdRoute
  AuthenticatedPaymentIndexRoute: typeof AuthenticatedPaymentIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBookRoute: AuthenticatedBookRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedRiderRoute: AuthenticatedRiderRoute,
  AuthenticatedPaymentOrderIdRoute: AuthenticatedPaymentOrderIdRoute,
  AuthenticatedTrackOrderIdRoute: AuthenticatedTrackOrderIdRoute,
  AuthenticatedPaymentIndexRoute: AuthenticatedPaymentIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BecomeRiderRoute: BecomeRiderRoute,
  ApiPublicMpesaCallbackRoute: ApiPublicMpesaCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
